# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Appli-Mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Appli-Mobile
  pod 'FirebaseUI'
  pod 'Firebase'  

  target 'Appli-MobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Appli-MobileUITests' do
    # Pods for testing
  end

end
